# Explore here

In [49]:
# Your code here
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [50]:
main_df = pd.read_csv('https://raw.githubusercontent.com/4GeeksAcademy/linear-regression-project-tutorial/main/medical_insurance_cost.csv')

In [51]:
main_df

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [52]:
main_df.describe()

age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [53]:
main_df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [54]:
main_df.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [55]:
main_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [56]:
sex_n = pd.factorize(main_df['sex'])[0]

In [57]:
sex_n

array([0, 1, 1, ..., 0, 0, 0])

In [58]:
smoker_n = pd.factorize(main_df['smoker'])[0]

In [59]:
region_n = pd.factorize(main_df['region'])[0]

In [60]:
quant_list = ['age','sex_n','bmi','children','smoker_n','region_n','charges']

In [61]:
quant_list

['age', 'sex_n', 'bmi', 'children', 'smoker_n', 'region_n', 'charges']

In [62]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [63]:
main_df.dtypes

age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
charges     float64
dtype: object

In [64]:
main_df['region_n'] = region_n


In [65]:
main_df['sex_n'] = sex_n

In [66]:
main_df['smoker_n'] = smoker_n

In [67]:
main_df

age     sex     bmi  children smoker     region      charges  region_n  \
0      19  female  27.900         0    yes  southwest  16884.92400         0   
1      18    male  33.770         1     no  southeast   1725.55230         1   
2      28    male  33.000         3     no  southeast   4449.46200         1   
3      33    male  22.705         0     no  northwest  21984.47061         2   
4      32    male  28.880         0     no  northwest   3866.85520         2   
...   ...     ...     ...       ...    ...        ...          ...       ...   
1333   50    male  30.970         3     no  northwest  10600.54830         2   
1334   18  female  31.920         0     no  northeast   2205.98080         3   
1335   18  female  36.850         0     no  southeast   1629.83350         1   
1336   21  female  25.800         0     no  southwest   2007.94500         0   
1337   61  female  29.070         0    yes  northwest  29141.36030         2   

      sex_n  smoker_n  
0         0         0  
1         1         1  
2         1         1  
3         1         1  
4         1         1  
...     ...       ...  
1333      1         1  
1334      0         1  
1335      0         1  
1336      0         1  
1337      0         0  

[1338 rows x 10 columns]

In [68]:
main_df[quant_list]

age  sex_n     bmi  children  smoker_n  region_n      charges
0      19      0  27.900         0         0         0  16884.92400
1      18      1  33.770         1         1         1   1725.55230
2      28      1  33.000         3         1         1   4449.46200
3      33      1  22.705         0         1         2  21984.47061
4      32      1  28.880         0         1         2   3866.85520
...   ...    ...     ...       ...       ...       ...          ...
1333   50      1  30.970         3         1         2  10600.54830
1334   18      0  31.920         0         1         3   2205.98080
1335   18      0  36.850         0         1         1   1629.83350
1336   21      0  25.800         0         1         0   2007.94500
1337   61      0  29.070         0         0         2  29141.36030

[1338 rows x 7 columns]

In [69]:
duplicate_counts = {}
# Iterate through each column to count duplicates
for column in main_df.columns:
    duplicate_counts[column] = main_df.duplicated(subset=[column]).sum()
# Display the count of duplicates for each column
print(duplicate_counts)

{'age': 1291, 'sex': 1336, 'bmi': 790, 'children': 1332, 'smoker': 1336, 'region': 1334, 'charges': 1, 'region_n': 1334, 'sex_n': 1336, 'smoker_n': 1336}


In [70]:
main_df.drop_duplicates(inplace=True)

In [71]:
arr = scaler.fit_transform(main_df[quant_list])
df_1 = pd.DataFrame(arr, index=main_df.index, columns=quant_list)

In [72]:
df_1.dtypes

age         float64
sex_n       float64
bmi         float64
children    float64
smoker_n    float64
region_n    float64
charges     float64
dtype: object

In [73]:
from sklearn.model_selection import train_test_split

X = df_1.drop('charges', axis=1)
y = df_1['charges']


In [74]:
X

age  sex_n       bmi  children  smoker_n  region_n
0     0.021739    0.0  0.321227       0.0       0.0  0.000000
1     0.000000    1.0  0.479150       0.2       1.0  0.333333
2     0.217391    1.0  0.458434       0.6       1.0  0.333333
3     0.326087    1.0  0.181464       0.0       1.0  0.666667
4     0.304348    1.0  0.347592       0.0       1.0  0.666667
...        ...    ...       ...       ...       ...       ...
1333  0.695652    1.0  0.403820       0.6       1.0  0.666667
1334  0.000000    0.0  0.429379       0.0       1.0  1.000000
1335  0.000000    0.0  0.562012       0.0       1.0  0.333333
1336  0.065217    0.0  0.264730       0.0       1.0  0.000000
1337  0.934783    0.0  0.352704       0.0       0.0  0.666667

[1337 rows x 6 columns]

In [78]:
y.dtype

dtype('float64')

In [76]:

X_train,X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=4)

In [79]:
from sklearn.feature_selection import f_regression, SelectKBest
selection_model = SelectKBest(f_regression, k=5)
selection_model.fit(X_train, y_train)
var_1 = selection_model.get_support()

In [80]:
var_1

array([ True,  True,  True,  True,  True, False])

In [83]:
from sklearn.linear_model import LinearRegression

In [84]:
linreg = LinearRegression()

In [85]:
linreg.fit(X_train, y_train)

LinearRegression()

In [87]:
y_pred = linreg.predict(X_test)
y_pred

array([ 0.42352782,  0.15327521,  0.18132751,  0.17091334,  0.19254388,
        0.01419482,  0.23079054,  0.50582115,  0.57328599,  0.01336796,
        0.14797204,  0.53270248,  0.4114071 ,  0.2064661 ,  0.26022007,
        0.64166299,  0.16859692,  0.23510899,  0.60929581,  0.02519629,
        0.03009981,  0.22447872,  0.12237245,  0.04066942,  0.1226133 ,
        0.5031737 ,  0.58890915,  0.12578171,  0.50354509,  0.14509842,
       -0.01693087,  0.01042366,  0.20078112,  0.04701383,  0.13384356,
        0.0053371 ,  0.2342807 ,  0.23136569,  0.06381009, -0.02428616,
        0.20572731,  0.15736403,  0.09332433,  0.48503412,  0.13036625,
        0.17246458,  0.53059027,  0.08163592,  0.20534604,  0.20152814,
        0.09070055,  0.04587167,  0.40372039,  0.07591183,  0.02388576,
        0.17055276,  0.1868355 ,  0.0260197 , -0.04018943,  0.04471705,
        0.16806015,  0.09262445,  0.09681487,  0.16891172,  0.58511364,
        0.14040001,  0.07049626,  0.07754903,  0.16932746,  0.21

In [89]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
print(f'testing set r2 score {r2_score(y_test, y_pred)}')
print(f'testing set mean absolute error {mean_absolute_error(y_test, y_pred)}')
print(f'testing set mean squared error {np.sqrt(mean_squared_error(y_test, y_pred))}')

testing set r2 score 0.7244150380582827
testing set mean absolute error 0.06568758463778378
testing set mean squared error 0.09390286930122405
